lattice-endpoint: <LATTICE_ENDPOINT>
sandboxes-token: <SANDBOXES_TOKEN>

# client credentials
lattice-client-id: <YOUR_CLIENT_ID>
lattice-client-secret: <YOUR_CLIENT_SECRET>

# entity update frequency (seconds)
entity-update-rate-seconds: 1

# vessels to track
vessel-mmsi:
    - 730156067 # RM SEA TROUT
    - 368179250 # SEAHAWK
    - 368138010 # NEW YORK
# vessel data generation time interval (seconds)
ais-generate-interval-seconds: 1